# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set up a minimal openbox environment with VirtualBox Guest Additions.
$setup = <<-'SETUP'
# Mute annoying Perl locale warnings on each-and-every-dang apt invocation.
locale-gen en_US.UTF-8
localedef -i en_US -f UTF-8 en_US.UTF-8
export LANGUAGE=en_US.UTF-8 LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

# Clean out some preinstalled cruft before upgrading.
# These need to all be in one command, otherwise initramfs gets rebuilt repeatedly.
apt -qy purge debian-faq doc-debian gcc-9-base git gnustep-common install-info installation-report javascript-common man-db manpages modemmanager netpbm ppp nftables ntfs-3g os-prober packagekit packagekit-tools pinentry-qt plymouth plymouth-label qemu-utils reportbug scrot smartmontools sweeper tasksel termit upower usbutils xorg-docs-coretelnet
apt -qy --purge autoremove
dpkg -l | grep '^rc' | awk '{print $2}' | xargs apt -qy purge
apt -qy clean

# "fasttrack" is required for installing virtualbox-guest-x11
cat <<'FASTTRACK' | tee /etc/apt/sources.list.d/fasttrack.list
deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
FASTTRACK
apt -qy update
apt -qy install fasttrack-archive-keyring
apt -qy update

# Make sure everything is up to date.
apt -qy upgrade

# swapspace prevents OOM death on VMs
apt -qy install aptitude swapspace

apt -qy install lightdm openbox xorg virtualbox-guest-x11

mkdir -p /home/vagrant/.config/openbox

cat <<'AUTOSTART' | tee /home/vagrant/.config/openbox/autostart >/dev/null
# Disable any form of screen saver / screen blanking / power management
xset s off
xset s noblank
xset -dpms

AUTOSTART

cat <<'RCXML' | tee /home/vagrant/.config/openbox/rc.xml >/dev/null
<?xml version="1.0" encoding="UTF-8"?>
<openbox_config xmlns="http://openbox.org/3.4/rc" xmlns:xi="http://www.w3.org/2001/XInclude">

  <desktops>
    <number>4</number>
  </desktops>

  <applications>
    <application class="*">
      <decor>no</decor>
    </application>
  </applications>

</openbox_config>
RCXML
SETUP

Vagrant.configure("2") do |config|

    ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

    config.vm.box                   = "debian/bullseye64"
    config.vm.box_check_update      = false
  
    config.vm.provider "virtualbox" do |vb|
        vb.gui                      = true
        vb.memory                   = 1024
        vb.cpus                     = 1
        vb.check_guest_additions    = false
        vb.customize                  ['modifyvm', :id, '--clipboard-mode', 'bidirectional']
        vb.customize                  ['modifyvm', :id, '--draganddrop', 'bidirectional']
    end

    config.vm.provision "shell", inline: $setup

    config.trigger.after [:provision] do |t|
        t.name = "Rebooting"
        t.run = { :inline => "vagrant reload" }
    end

end
